{% set name = "bdbag" %}
{% set version = "1.6.4" %}
{% set sha256 = "bd6fb725bf32cf8dc82ec95dd4aaec57b5615452b611447aefbd325a9583228e" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  entry_points:
    - bdbag = bdbag.bdbag_cli:main
    - bdbag-utils = bdbag.bdbag_utils:main

requirements:
  host:
    - python >=3
    - pip
    - setuptools<6.0
  run:
    - python >=3.5
    - setuptools
    - pytz
    - tzlocal==2.1
    - requests>=2.7.0
    - certifi
    - bagit==1.8.1
    - bagit-profile==1.3.1

test:
  imports:
    - bdbag
  commands:
    - bdbag -h

about:
  home: https://github.com/fair-research/bdbag
  summary: A collection of software programs for working with BagIt packages.
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  description: |
    The bdbag utilities are a collection of software programs for working with
    BagIt packages that conform to the BDBag and Bagit/RO profiles.

    The bdbag profiles specify the use of the fetch.txt file, require
    serialization, and specify what manifests must be provided with a bdbag.

    These utilities combine various other components such as the Bagit-Python
    bag creation utility and the Bagit-Profiles-Validator utility into a single,
    easy to use software package.
  doc_url: https://github.com/fair-research/bdbag/blob/master/doc/
  dev_url: https://github.com/fair-research/bdbag

extra:
  recipe-maintainers:
    - mikedarcy
    - bernt-matthias
